
export const bakeryLabels = {
  // Product Form Modal
  editProduct: "பொருளைத் திருத்து",
  addProduct: "புதிய பேக்கரி பொருள் சேர்",
  formSubtitle: "பொருள் விவரங்கள், புகைப்படங்கள், விலை, இருப்பு வரம்புகளை புதுப்பிக்கவும்",
  imageSectionTitle: "பொருள் படம்",
  tabPresets: "முன்னமைவுகள்",
  tabUpload: "கோப்பு பதிவேற்று",
  tabUrl: "இணைய இணைப்பு",
  choosePreset: "பேக்கரி இனிப்பு படங்களிலிருந்து தேர்ந்தெடுக்கவும்:",
  clickOrDrop: "பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
  livePreview: "நேரடி POS & இன்வாய்ஸ் முன்னோட்டம்",
  uploadInstruction: "உங்கள் சாதனத்திலிருந்து படத்தை பதிவேற்றவும் (PNG, JPG, WEBP):",
  clickToSelect: "தேர்ந்தெடுக்க கிளிக் செய்யவும் அல்லது படத்தை இங்கே இழுக்கவும்",
  autoCompress: "உயர்தர சுருக்கம் தானாக செய்யப்படும்",
  uploadSuccess: "தனிப்பயன் புகைப்படம் வெற்றிகரமாக பதிவேற்றப்பட்டது",
  pasteUrl: "படத்தின் இணைப்பை ஒட்டவும் (Unsplash, இணைய இணைப்பு, போன்றவை):",
  urlPlaceholder: "https://images.unsplash.com/...",
  urlError: "இந்த இணைப்பிலிருந்து படத்தை ஏற்ற முடியவில்லை. இணைப்பை சரிபார்க்கவும்.",
  productName: "பொருளின் பெயர் *",
  productNamePlaceholder: "எ.கா. ஸ்பெஷல் காஜு கத்லி",
  productCode: "பொருள் குறியீடு / SKU",
  productCodePlaceholder: "SW-101",
  category: "வகை",
  unit: "அளவீட்டு அலகு",
  sellingPrice: "விற்பனை விலை (₹) *",
  costPrice: "விலை (₹)",
  gstRate: "GST விகிதம் (%)",
  gstNil: "0% (வரி இல்லை)",
  gstStandard: "5% (நிலையான பேக்கரி)",
  gstConfectionery: "12% (மிட்டாய் வகை)",
  gstLuxury: "18% (பேக் செய்யப்பட்ட சிறப்பு)",
  currentStock: "தற்போதைய இருப்பு",
  lowStockLimit: "குறைந்த இருப்பு எச்சரிக்கை வரம்பு",
  highDemand: 'அதிக தேவை கொண்ட பொருளாக குறிக்கவும் (டாஷ்போர்டில் தங்க/பச்சை பேட்ஜுடன் காட்டப்படும்)',
  cancel: "ரத்து செய்",
  saveChanges: "மாற்றங்களை சேமி",
  addToInventory: "பட்டியலில் சேர்",
  uploadNewImage: "புதிய படத்தை பதிவேற்று",
  removeImage: "படத்தை நீக்கு",
  clearLink: "இணைப்பை அழி",
  productPreviewAlt: "பொருள் முன்னோட்டம்",

  // Products View (list/table/grid screen)
  pageTitle: "பொருட்கள் பட்டியல்",
  pageSubtitle: "இனிப்பு பொருட்கள், விலைகள், மற்றும் இருப்பு வரம்புகளை நிர்வகிக்கவும்",
  tableViewTitle: "அட்டவணை பார்வை",
  gridViewTitle: "கட்ட பார்வை",
  addProductBtn: "பொருள் சேர்",
  searchPlaceholder: "பொருளின் பெயர் அல்லது குறியீட்டைத் தேடவும்...",
  filterAll: "அனைத்தும்",
  filterInStock: "இருப்பில் உள்ளது",
  filterLowStock: "குறைந்த இருப்பு",
  filterOutOfStock: "இருப்பு இல்லை",
  categoryAll: "அனைத்தும்",
  failedToLoad: "பொருட்களை ஏற்ற முடியவில்லை",
  retryProducts: "மீண்டும் முயற்சிக்கவும்",
  noProductsFound: "பொருட்கள் எதுவும் இல்லை",
  noProductsHintFilter: "உங்கள் தேடல் அல்லது வடிகட்டியை மாற்றி முயற்சிக்கவும்.",
  noProductsHintEmpty: "உங்கள் முதல் இனிப்பு அல்லது பேக்கரி பொருளை சேர்க்கவும்.",
  addNewProduct: "புதிய பொருள் சேர்",
  colItemDetails: "பொருள் விவரம்",
  colCategory: "வகை",
  colSellingPrice: "விற்பனை விலை",
  colGstRate: "GST விகிதம்",
  colStockLevel: "இருப்பு அளவு",
  colStatus: "நிலை",
  colActions: "செயல்கள்",
  statusOutOfStock: "இருப்பு இல்லை",
  statusLowStock: "குறைந்த இருப்பு",
  statusInStock: "இருப்பில் உள்ளது",
  editProductTitle: "பொருளைத் திருத்து",
  deleteProductTitle: "பொருளை நீக்கு",
  hsnLabel: "HSN",
};
export const bulkOrderLabels = {
  modalTitle: "மொத்த / கேட்டரிங் ஆர்டர் உருவாக்கு",
  modalSubtitle: "திருமணங்கள், பண்டிகை பரிசுப் பெட்டிகள், நிகழ்ச்சி இனிப்புகளை பதிவு செய்யவும்",

  // Customer Information
  customerInfoHeading: "வாடிக்கையாளர் தகவல்",
  customerName: "வாடிக்கையாளர் பெயர் *",
  customerNamePlaceholder: "எ.கா. ரமேஷ் சந்திரா",
  phoneNumber: "தொலைபேசி எண் *",
  phonePlaceholder: "98401 23456",
  emailOptional: "மின்னஞ்சல் (விருப்பத்திற்குரியது)",
  emailPlaceholder: "name@gmail.com",

  // Delivery & Schedule
  deliveryScheduleHeading: "டெலிவரி & அட்டவணை",
  deliveryDate: "டெலிவரி தேதி *",
  deliveryTime: "டெலிவரி நேரம் *",
  deliveryMode: "டெலிவரி முறை",
  homeDelivery: "வீட்டிற்கு டெலிவரி",
  storePickup: "கடையில் வந்து பெறுதல்",
  occasion: "நிகழ்வு",
  occasionWedding: "திருமணம்",
  occasionBirthday: "பிறந்தநாள் விழா",
  occasionFestival: "பண்டிகை (தீபாவளி/பொங்கல்)",
  occasionCorporate: "நிறுவன நிகழ்வு",
  occasionReligious: "பூஜை / மத நிகழ்வு",
  occasionOther: "மற்ற நிகழ்வு",
  deliveryAddress: "டெலிவரி இடம் / முகவரி",
  deliveryAddressPlaceholder: "மண்டப பெயர், கதவு எண், தெரு பெயர், பகுதி...",
  addressDefaultPickup: "கவுண்டர் பிக்அப் (Royal Sweets Store)",
  addressDefaultConfirm: "பின்னர் உறுதிப்படுத்தப்படும்",

  // Bulk Order Items
  orderItemsHeading: "மொத்த ஆர்டர் பொருட்கள்",
  addItemRow: "பொருள் வரிசை சேர்",
  loadingProducts: "பொருட்கள் ஏற்றப்படுகின்றன...",
  errorLoadingProducts: "பொருட்களை ஏற்ற முடியவில்லை.",
  noProductsAvailable: "பொருட்கள் எதுவும் இல்லை.",
  unitLabel: "அலகு",

  // Payment & Instructions
  specialInstructions: "சிறப்பு வழிமுறைகள் / பேக்கிங் குறிப்பு",
  specialInstructionsPlaceholder: "எ.கா. 250g தனித்தனி பரிசு பெட்டிகள், ரிப்பன் பேக்கிங், கேக்கில் நட்ஸ் வேண்டாம்...",
  totalOrderAmount: "மொத்த ஆர்டர் தொகை:",
  advanceReceived: "முன்பணம் பெறப்பட்டது:",
  remainingBalance: "மீதமுள்ள தொகை:",

  // Footer
  cancel: "ரத்து செய்",
  saving: "சேமிக்கிறது...",
  saveBulkOrder: "மொத்த ஆர்டரை சேமி",
};
export const billingLabels = {
  searchPlaceholder: "இனிப்பு பெயர் அல்லது குறியீடு தேடு...",
  itemsCountSuffix: "பொருட்கள்",
  categoryAll: "அனைத்தும்",

  outOfStock: "இல்லை",
  lowStockPrefix: "குறைவு",
  inCartSuffix: "கூடையில்",

  cartHeading: "என் கூடை",
  clear: "அழி",

  cartEmptyTitle: "கூடை காலியாக உள்ளது",
  cartEmptyHint: "பொருளைத் தொட்டு சேர்க்கவும்",

  subtotalLabel: "மொத்தம் (பொருட்கள்):",
  taxLabel: "வரி:",
  totalToPay: "கொடுக்க வேண்டிய தொகை:",

  paymentMethodLabel: "பணம் செலுத்தும் விதம்",
  payCash: "பணம்",
  payUpi: "UPI",
  payCard: "கார்டு",
  paySplit: "பிரித்து",

  cashGiven: "கொடுத்த பணம்:",
  quickLabel: "விரைவு:",
  changeToGive: "திருப்பிக் கொடுக்க வேண்டியது:",

  makeBillBtn: "பில் தயார் செய்",
  savingBillBtn: "பில் தயாராகிறது...",
};
export const invoicesLabels = {
  pageTitle: "விற்பனை பில்கள் & ரசீதுகள்",
  pageSubtitle: "அனைத்து கவுண்டர் பில்கள், GST இன்வாய்ஸ், வாடிக்கையாளர் பரிவர்த்தனைகளின் வரலாறு",

  totalRevenueLabel: "மொத்த வருவாய்",
  invoicesGeneratedSuffix: "பில்கள் உருவாக்கப்பட்டது",
  cashCollectionLabel: "பணப் பெட்டி தொகை",
  drawerCashTotal: "பணப்பெட்டி மொத்தம்",
  upiCollectionLabel: "UPI / QR வசூல்",
  settledToBank: "வங்கிக்கு செலுத்தப்பட்டது",

  searchPlaceholder: "பில் எண், வாடிக்கையாளர் பெயர், எண் தேடவும்...",

  filterAll: "அனைத்தும்",
  filterCash: "பணம்",
  filterUpi: "UPI",
  filterCard: "கார்டு",

  failedToLoad: "பில்களை ஏற்ற முடியவில்லை",
  retryLoading: "மீண்டும் முயற்சிக்கவும்",

  colInvoiceNumber: "பில் எண்",
  colDateTime: "தேதி & நேரம்",
  colCustomer: "வாடிக்கையாளர்",
  colItems: "பொருட்கள்",
  colPayment: "பணம் செலுத்தல்",
  colTotalAmount: "மொத்த தொகை",
  colStatus: "நிலை",
  colReceipt: "ரசீது",

  noInvoicesFound: "பில்கள் எதுவும் இல்லை",
  noInvoicesHint: "POS மெஷினில் பில் உருவாக்கினால் இங்கே தெரியும்.",

  itemsSuffix: "பொருட்கள்",
  statusPaid: "செலுத்தப்பட்டது",

  previewInvoiceTitle: "பில்லைப் பார்",
  printBillBtn: "பில் அச்சிடு",
};